version: '3'

services:
  proxy:
    image: traefik:1.3.5
    command: --web --docker --logLevel=DEBUG --acme.acmelogging=true --acme=true --acme.email=michael.donat@me.com --acme.entrypoint=https --acme.onhostrule=true --acme.storage=/etc/acme/acme.json --entryPoints='Name:https Address::443 TLS'  --defaultentrypoints=https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - acme:/etc/acme/

  landing:
    image: michaeldonat/me.landing
    labels:
      - "traefik.backend=landing"
      - "traefik.frontend.rule=Host:michael-donat.me"
      - "traefik.frontend.entryPoints=http,https"

  recipes:
    image: wordpress:php7.2-apache
    env_file: [./secrets/wp.env]
    environment:
      - WORDPRESS_DB_NAME=blog_przepisy
    ports:
      - "81:8080"
      - "82:80"
    links:
      - "recipes_db:mysql"
    labels:
      - "traefik.backend=recipes"
      - "traefik.frontend.rule=Host:przepisy.thedonats.net"
      - "traefik.frontend.entryPoints=http,https"
    volumes:
      - "recipes_data:/var/www/html/wp-content"

  recipes_db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - recipes_db:/var/lib/mysql
    env_file: [./secrets/wp.env]
    labels:
      - "traefik.enable=false"

volumes:
  acme:
  recipes_db:
  recipes_data:
