version: '3'

services:
  proxy:
    image: traefik:1.3.5
    command: --web --docker --logLevel=DEBUG --acme.acmelogging=true --acme=true --acme.email=michael.donat@me.com --acme.entrypoint=https --acme.onhostrule=true --acme.storage=/etc/acme/acme.json --entryPoints='Name:https Address::443 TLS'  --defaultentrypoints=https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - acme:/etc/acme/

  landing:
    image: michaeldonat/me.landing
    labels:
      - "traefik.backend=landing"
      - "traefik.frontend.rule=Host:michael-donat.me"
      - "traefik.frontend.entryPoints=http,https"

volumes:
  acme:
